spring.application.name=Art Class Management

# Server port - Render injects PORT env variable
server.port=${PORT:8080}

# PostgreSQL - set these in Render's Environment Variables
spring.datasource.url=jdbc:postgresql://artclass_db_user:7NPBEunEoMdyvGyHP9evhrmWZLNXCXIZ@dpg-d7il9unlk1mc73a0j5k0-a/artclass_db
spring.datasource.password=7NPBEunEoMdyvGyHP9evhrmWZLNXCXIZ
spring.datasource.username=artclass_db_user
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=false