spring.application.name=Art Class Management

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d7il9unlk1mc73a0j5k0-a:5432/artclass_db
spring.datasource.username=artclass_db_user
spring.datasource.password=7NPBEunEoMdyvGyHP9evhrmWZLNXCXIZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.thymeleaf.cache=false