
spring.application.name=Art Class Management

spring.datasource.url=${postgresql://artclass_db_user:7NPBEunEoMdyvGyHP9evhrmWZLNXCXIZ@dpg-d7il9unlk1mc73a0j5k0-a/artclass_db}
spring.datasource.username=${artclass_db_user}
spring.datasource.password=${7NPBEunEoMdyvGyHP9evhrmWZLNXCXIZ}



server.port=${5432}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Thymeleaf
spring.thymeleaf.cache=false


